apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: helloworld
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
